### ISSUE TITLE
只支持表单验证吗？能支持双向数据绑定不？

### ISSUE THREAD

**Issue by dongweb** [zmrdlb/react-native-form-verify#1]
只支持表单验证吗？能支持双向数据绑定不？

**Comment by zmrdlb** [comment]
其实react-native本身支持实现双向数据绑定，可变数据都声明在this.state里面，使用方式在readme里面也写清楚了，此次截图说明。
![image](https://user-images.githubusercontent.com/6328436/34150470-6708a372-e4e3-11e7-8ec5-409fa97afac0.png)
